### ISSUE TITLE
Docker image: ImportError: cannot import name 'get_orbit_file_from_list' from 's1reader.s1_orbit' 

### ISSUE THREAD

**Issue by Narayana-Rao** [opera-adt/RTC#10]
Facing the following issue while trying to run a container from a successfully built docker image. I tried to install it manually but ```import RTC``` is working instead ```import rtc``` again throwing the same error as below (after fixing for case sensitive ```import``` ). Could you please help. 

### On DOCKER 

```
ERROR conda.cli.main_run:execute(41): `conda run rtc_s1.py` failed. (See above for error)
Traceback (most recent call last):
  File "/home/rtc_user/miniconda3/envs/isce3_rtc/bin/rtc_s1.py", line 20, in <module>
    from rtc.runconfig import RunConfig
  File "/home/rtc_user/miniconda3/envs/isce3_rtc/lib/python3.9/site-packages/rtc/runconfig.py", line 19, in <module>
    from s1reader.s1_orbit import get_orbit_file_from_list
ImportError: cannot import name 'get_orbit_file_from_list' from 's1reader.s1_orbit' (/home/rtc_user/miniconda3/envs/isce3_rtc/lib/python3.9/site-packages/s1reader/s1_orbit.py)
```

### Manual Installation

```
Traceback (most recent call last):
  File "//home/RTC/app/rtc_s1.py", line 20, in <module>
    from rtc.runconfig import RunConfig
  File "/home/RTC/src/rtc/runconfig.py", line 19, in <module>
    from s1reader.s1_orbit import get_orbit_file_from_list
ImportError: cannot import name 'get_orbit_file_from_list' from 's1reader.s1_orbit' (/usr/local/lib/python3.10/dist-packages/s1reader/s1_orbit.py)
```

**Comment by seongsujeong** [comment]
There has been a change on one of the dependencies of this software (i.e. [s1-reader](https://github.com/opera-adt/s1-reader)) The error message was because the changes has removed the function `get_orbit_file_from_list` in the `s1-reader`

I have submitted a PR to revive the function, which was merged recently. Please pull the most recent version of `s1-reader` and it should work now.

**Comment by gshiroma** [comment]
This issue was resolved (see @seongsujeong  message above).
