### ISSUE TITLE
Geogrid module

### ISSUE THREAD

**Issue by seongsujeong** [opera-adt/RTC#2]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Geogrid module needs to be tested in more general cases

### Describe the feature request

I need or want [...]

**Comment by gshiroma** [comment]
This issue has been resolved by [this commit](https://github.com/opera-adt/RTC/commit/e94c486e146f78a7b6f9d277ac36ed7cc48bd060#diff-7ccdeaede3f7df6cf8deda53e07f6ef3295fb6dae837c8d6d04f33bac40d66b4).
