### ISSUE TITLE
[New Feature]: Suggestions for RTC-S1 metadata

### ISSUE THREAD

**Issue by vbrancat** [opera-adt/RTC#40]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Some of metadata generated by the RTC workflow seem to be not pertinent to Sentinel-1. Below, some suggestions based on discussions had internally to the OPERA CSLC-S1 team. Feel free to use or disregard them as you see fit.

### Describe the feature request

Based on the main branch `RTC/h5_prep.py`

1. [`platform_id`](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L267) and [`sensor`](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L269) in the `identification` group contain the same metadata value i.e., `platform_id`
2. [acquisitionMode](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L274) seems to be hard-coded to IW. Sentinel supports also EW which can be used to generate RTC products.
3. [listOfFrequencies](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L284) seems to be a NISAR heritage. Sentinel will not have multiple frequency bands. Consider removing it.
4. [isUrgentObservation](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L296) no urgent observation foreseen for Sentinel or by the project
5. [diagnosticModeFlag](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L299) not pertinent to Sentinel
6. [softwareVersion](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L312) should not be contained in `identification` but in `processing_information`. Unclear which software correspond to (RTC? ISCE3?)
7. [ISCEVersion](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L352) should be `ISCE3Version`
8. Include RTC software version in `processingInformation/algorithms`
9. [configFiles](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L370) will not be populated with anything meaningful. Most likely PCM will archive the runconfigs and this metadata will not contain the location of the archived runconfig. Consider replacing it with the content of the runconfiguration file
10. [beamID](https://github.com/opera-adt/RTC/blob/5bd6cfddc8724279a189f754ede904d4f760414c/src/rtc/h5_prep.py#L390) May be subswath?

For CSLC-S1 we decided to use
1. snake case (RTC is using camel case)
2. Remove `/science/SENTINEL1`
3. Rename the `grids` group to `data`
4. Remove `frequencyA` nomenclature

**Comment by gshiroma** [comment]
Thank you, @vbrancat !

**Comment by gshiroma** [comment]
Hi @vbrancat , we addressed all your comments. Overall. we removed the metadata structure and parameters from NISAR products that did not make sense for RTC-S1 product. Addressing your comments point per point:
- We removed inconsistencies between `platform_id` and `sensor`. The `platform_id` was renamed to `platform` and we removed `sensor`.
- `acquisitionMode` is not hard-coded anymore.
-  We decided to keep the `diagnosticModeFlag`.
- `softwareVersion` was moved to `processingInformation/algorithms`
- We removed `configFiles`
- `beamID` was renamed to `subSwathID`.

We also did similar changes for RTC-S1 compared to CSLC products:

- We kept camel case in the HDF5 metadata, but had snake case for the GeoTIFF metadata;
- Removed the group `/science/CSAR`
- Renamed the group `grids` to `data`
- Removed `frequencyA`.

 Your comments were very helpful! Thanks again!
