### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by seongsujeong** [opera-adt/RTC#6]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Related problems

We need an instruction for installing and using this workflow.

### Describe the feature request

I need or want [...]

**Comment by gshiroma** [comment]
This issue has been resolved by this [PR](https://github.com/opera-adt/RTC/pull/20).

**Comment by gshiroma** [comment]
This issue has been resolved by this [PR](https://github.com/opera-adt/RTC/pull/20).
