### ISSUE TITLE
[New Feature]: Provide browse images with width/height no larger than the source GeoTIFFs

### ISSUE THREAD

**Issue by asjohnston-asf** [opera-adt/RTC#78]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

The browse png files for RTC products appear to always have a height of 2,048 pixels and variable width. That leads to browse images that are *bigger* than the source GeoTIFFs. It feels counter-productive to generate and archive a browse image that is bigger than the source data.

For example, for `OPERA_L2_RTC-S1_T011-022407-IW3_20231019T111059Z_20231019T214052Z_S1A_30_v1.0` published at ASF, the source GeoTIFFs are 3092 x 1513 pixels (6.2 MB and 5.9 MB), while the PNG browse image is 4185 x 2048 pixels (9.8 MB).

### Describe the feature request

I suggest setting the height of the browse PNG to the minimum of the configured browse height and the source GeoTIFF height.

**Comment by mckadesorensen** [comment]
@asjohnston-asf I think this issue comes from a request we made. We asked the OPERA SDS to set one side to 2048. We should have specified that we wanted the larger side to be set to 2048.

**Comment by gshiroma** [comment]
Thank you, @asjohnston-asf and @mckadesorensen . Yes, we changed the default browse image heights to `2048` [here](https://github.com/opera-adt/RTC/blob/70d42164a5ebff07165f551c619b3e3da2a5e51d/src/rtc/defaults/rtc_s1.yaml#L319) and [here](https://github.com/opera-adt/RTC/blob/70d42164a5ebff07165f551c619b3e3da2a5e51d/src/rtc/defaults/rtc_s1_static.yaml#L320) to address a request made by ASF to the OPERA SDS. Please, notice that these values are only default values and can be changed using the runconfig file when running the SAS.
