### ISSUE TITLE
[Bug]: RTC-S1 SAS fails on SLC Granule S1A_IW_SLC__1SDV_20230114T161231_20230114T161258_046782_059BD6_D15F

### ISSUE THREAD

**Issue by collinss-jpl** [opera-adt/RTC#86]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

A particular RTC-S1 job fails with the following error when running on SLC granule S1A_IW_SLC__1SDV_20230114T161231_20230114T161258_046782_059BD6_D15F:

```
[StdErr] Traceback (most recent call last):
[StdErr]   File "/home/rtc_user/miniconda3/envs/RTC/bin/rtc_s1_single_job.py", line 35, in <module>
[StdErr]     run_single_job(cfg)
[StdErr]   File "/home/rtc_user/miniconda3/envs/RTC/lib/python3.9/site-packages/rtc/rtc_s1_single_job.py", line 1656, in run_single_job
[StdErr]     rg_lut, az_lut = compute_correction_lut(
[StdErr]   File "/home/rtc_user/miniconda3/envs/RTC/lib/python3.9/site-packages/rtc/rtc_s1_single_job.py", line 243, in compute_correction_lut
[StdErr]     gdal.Open(f'{scratch_path}/height.rdr', gdal.GA_ReadOnly).ReadAsArray()
[StdErr]   File "/home/rtc_user/miniconda3/envs/RTC/lib/python3.9/site-packages/osgeo/gdal.py", line 5296, in Open
[StdErr]     return _gdal.Open(*args)
[StdErr] RuntimeError: DSI or ACC record missing.  DTED access to
[StdErr] /home/rtc_user/scratch_dir/temp_1712164165.8587625/temp_1712164170.0907102/t160_342212_iw1//height.rdr failed.
```

Additionally, because a single worker thread failed, the SAS now attempts to delete everything from the output directory, _including the output directory itself_, which results in the following additional error:

```
[StdErr] Traceback (most recent call last):
[StdErr]   File "/home/rtc_user/miniconda3/envs/RTC/bin/rtc_s1.py", line 41, in <module>
[StdErr]     main()
[StdErr]   File "/home/rtc_user/miniconda3/envs/RTC/bin/rtc_s1.py", line 36, in main
[StdErr]     run_parallel(cfg, path_logfile_parent, flag_full_log_formatting)
[StdErr]   File "/home/rtc_user/miniconda3/envs/RTC/lib/python3.9/site-packages/rtc/rtc_s1.py", line 627, in run_parallel
[StdErr]     os.rmdir(output_dir)
[StdErr] PermissionError: [Errno 13] Permission denied: '/home/rtc_user/output_dir'
```

When running the SAS in the SDS, the output directory is always mounted from the file system outside of the container, so the SAS should never try to delete this directory (deleting the contents within the output directory is OK though)

### What did you expect?

Please confirm if the "DSI or ACC record missing" error is due to a defect in the input SLC granule, or if this can be fixed within the RTC code. The RTC code should also be updated to [remove this block of code](https://github.com/opera-adt/RTC/blob/f92a38bbf19d33994bfb9f610f74a74c44bd5e8f/src/rtc/rtc_s1.py#L623-L627), but this is less critical.

### Reproducible steps

```bash
Inputs and a sample RunConfig can be found in the following S3 location: s3://opera-dev-triage-fwd-collinss/triaged_job-SCIFLO_L2_RTC_S1__issue_775_disp_s1_v3.0.0-rc.2.0_integration-S1A_IW_SLC__1SDV_20230114T161231_20230114T161258_046782_059BD6_D15F-r2-20240403T165711.673086Z_task-dbe0456c-a6ec-432e-9651-d94a076386e0/
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by gshiroma** [comment]
This issue was addressed in PR #87. I'm closing it now. Thanks again, @collinss-jpl .
